addons: 
  chrome: stable
before_script:
 - "chmod +x ./test/selenium_test.py"
install: 
  - "pip install selenium"
languages: python
python: 
  - "3.6"
  - "3.7"
script: 
  - ./test/selenium_test.py
